title: "Santosh Vasudevan"
author: "Santosh Vasudevan"
description: "Made with ♥ in Chicago"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_social: true         # show footer
show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title : HOME}
  - {file: "aboutme.md", title : ABOUT ME}
  - {file: "projects.md", title : PROJECTS}
  - {file: "blog.md", title : BLOG}
  - {file: "imagetest.md", title : IMAGE TEST}




external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/san-to-sh"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/santoiscurious"}
  - {title: Medium, icon: medium, url: "https://medium.com/@santoshsrivatsa"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/santoshsrivatsa"}
  


remote_theme: niklasbuschmann/contrast@v2.11

plugins:
  - jekyll-remote-theme
  - jekyll-feed

